#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.xyz"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	eww daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	eww open-many weather profile quote search_full incognito-icon vpn-icon home_dir screenshot power_full reboot_full lock_full logout_full suspend_full
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	eww close-all
	rm "$FILE"
fi

